set_entity:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: service_entities
          domain: sensor
    state:
      required: true
    # Optionals:
    attributes:
      required: false
    name:
      required: false
    icon:
      required: false
    unit_of_measurement:
      required: false

delete_entity:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: service_entities
          domain: sensor
